AWSTemplateFormatVersion: 2010-09-09
Description: Eric Kasakya / Software Engineer - This is CloudFormations deploys VPC
Resources:
  mycfVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: True
      EnableDnsSupport: True
      Tags: 
        - Key: env
          Value: test